# src/nfcscript/__init__.pyi
from typing import Any
from .reader import NfcReader
from .types import TagProtocol
from .assertions import ASSERT_EQUAL as ASSERT
from .registry import register, get

# --- 基础导出 ---
#   ASSERT: from .assertions
#   ASSERT_LEN: from .assertions (未公开导入，见 nuts 模块)
#   NfcReader: from .reader
#   register, get: from .registry

# --- 核心 ---
def init_nfc(hardware: str = ..., driver: str = ..., port: str = ...) -> NfcReader: ...
def get_active_tag() -> TagProtocol: ...

# --- NfcReader 方法（_make_wrapper 自动创建）---
def bind_card(card_name: str, uid: bytes = ...) -> Any: ...
def find_card() -> Any: ...
def find_raw() -> dict: ...
def transceive(data: bytes, **kwargs: Any) -> bytes: ...

# --- NfcReader 属性（_make_wrapper 自动创建，不调用 callable 直接返回）---
def driver() -> Any: ...
def active_tag() -> TagProtocol: ...

# --- ASSERT 方法 ---
def ASSERT(actual: Any, expected: Any) -> None: ...

# --- 卡片转发方法（通过 NfcReader.__getattr__ 转发到 active_tag）---
def get_version() -> bytes: ...
def read(addr: int, length: int) -> bytes: ...
def write(addr: int, data: bytes) -> None: ...
def fast_read(addr: int, length: int) -> bytes: ...
def fast_write(addr: int, data: bytes) -> None: ...
def get_uid() -> bytes: ...
def get_sig() -> bytes: ...
