# src/nfcscript/reader.pyi
from typing import Optional, Any
from .types import TagProtocol

class NfcReader:
    active_tag: Optional[TagProtocol]
    def __init__(self, hardware_name: str, driver_name: str, port: str) -> None: ...
    def bind_card(self, card_name: str, uid: bytes = ...) -> Any: ...
    def find_raw(self) -> dict: ...
    def find_card(self) -> Any: ...
    def transceive(self, data: bytes, **kwargs: Any) -> bytes: ...
    @property
    def driver(self) -> Any: ...
