from typing import Protocol, Any

class TagProtocol(Protocol):
    """IDE 看到的卡片插件通用契约"""
    def get_version(self) -> bytes: ...
    # 可以在此添加更多通用的卡片方法
    def read_data(self, addr: int, length: int) -> bytes: ...
    def write_data(self, addr: int, data: bytes) -> None: ...

class ReaderProtocol(Protocol):
    """IDE 看到的读卡器通用契约"""
    def bind_card(self, card_name: str, uid: bytes = b'\x00' * 7) -> Any: ...
    def find_card(self) -> Any: ...
