# src/nfcscript/types.pyi
from typing import Protocol

class TagProtocol(Protocol):
    def get_version(self) -> bytes: ...
    def read_data(self, addr: int, length: int) -> bytes: ...
    def write_data(self, addr: int, data: bytes) -> None: ...

class ReaderProtocol(Protocol):
    def bind_card(self, card_name: str, uid: bytes = ...) -> Any: ...
    def find_card(self) -> Any: ...
